mkdir "C:\Program Files (x86)\Renewed Vision"
mkdir "C:\Program Files (x86)\Renewed Vision\ProPresenter 6"
mkdir "C:\Users\%username%\Documents\ProPresenter6"
copy  C:\BackupProPresenter6\ProPresenterF "C:\Program Files (x86)\Renewed Vision\ProPresenter 6"
copy  C:\BackupProPresenter6\ProPresenterD "C:\Users\%username%\Documents\ProPresenter6"